name: kTekkitAdjustments
main: com.khell.bukkit.kTekkitAdjustments.kTekkitAdjustments
version: 1.0
commands:
    kTekkitAdjustments:
        description: kTekkitAdjustments, targeting Tekkit 3.1.3, Minecraft 1.2.5.
        usage: /kTekkitAdjustments
        permission: kTekkitAdjustments.kTekkitAdjustments
        permission-message: You don't have permission to use this command.
